### PR TITLE
Add a pagination widget

### LINKED ISSUE #31: Page numbers
We need a page number widget to be able to more easily navigate approval lists

### PR DESCRIPTION
**Pull request by gregory-latinier**
Fix #31 
Add an input where the user types the page number and hit enter.

### CODE REVIEW

**Comment by jnordberg** [comment]
This is not what that issue refers to, this is a page navigation widget:

screen shot 2018-02-16 at 12 39 19

**Comment by gregory-latinier** [comment]
Sure I'll change it

**Comment by bonustrack** [comment]
@gregory-latinier Page 2 link is visible even when there is only 3 results available on the first page:
image
Can you fix that?

Also the name of the var `elements` is confusing. I would rather name it `itemsPerPage`.

**Comment by bonustrack** [comment]
@jnordberg can we merge that PR?

**Comment by jnordberg** [comment]
Does this work with the search view also?

**Comment by gregory-latinier** [comment]
This pagination will be added to search and audit once merged

**Pull request merged**
